version: '3'
services:
  db:
    container_name: db
    image: postgres:13.3
    command: >
      postgres -c 'max_connections=200'
      -c 'shared_buffers=2GB'
      -c 'effective_cache_size=6GB'
      -c 'maintenance_work_mem=512MB'
      -c 'checkpoint_completion_target=0.9'
      -c 'work_mem=5242kB'
      -c 'min_wal_size=4GB'
      -c 'max_wal_size=2GB'
      -c 'max_worker_processes=16'
      -c 'max_parallel_workers_per_gather=4'
      -c 'max_parallel_workers=16'
      -c 'max_parallel_maintenance_workers=4'
    env_file:
      - ./docker-compose.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
    restart: unless-stopped

volumes:
  postgres_data: